query{
    product(slug: "lava-e-seca-brastemp-ative-10kg-6kg-branca-bns10ab"){
        productName
        linkText
        items{
        referenceId{
            Value
        }
        images{
            imageUrl
        }
        sellers{
            addToCartLink
            sellerDefault
            commertialOffer{
            Price
            ListPrice
            Installments{
                Value
                InterestRate
                TotalValuePlusInterestRate
                NumberOfInstallments
                PaymentSystemName
                PaymentSystemGroupName
                Name
            }
            }
        }
        
        }
    }
}